//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace Contoso.WebControls.FieldControls.CONTROLTEMPLATES {
    
    
    public partial class Contoso {
        
        /// <summary>
        /// ProductCodeRenderingTemplate control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Microsoft.SharePoint.WebControls.RenderingTemplate ProductCodeRenderingTemplate;
        
        /// <summary>
        /// ProductCodeDisplayRenderingTemplate control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Microsoft.SharePoint.WebControls.RenderingTemplate ProductCodeDisplayRenderingTemplate;
    }
}
